name: Generate 3D Profile Card

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate 3D Profile Card
        run: |
          echo "3D Profile Card is generated via API call in README"
          echo "No additional workflow needed" 